name: simple_circles_examples
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gradients: ^1.0.0+2
  simple_circles:
    path: ../

flutter:
  uses-material-design: true

  assets:
    # Taken from SF Textures (https://sftextures.com/)
    - assets/clock_texture.jpg
